### ISSUE TITLE
Returns no state but memory location.

### ISSUE THREAD

**Issue by jeffasante** [elvisyjlin/gym-chrome-dino#3]
As
`env = gym.make('CartPole-v0').unwrapped
`
`env.reset()`

Returns
`
array([ 0.0286644 , -0.0473783 , -0.01396534,  0.03493663])
`

Your agent returns memory location, why that?

**Comment by elvisyjlin** [comment]
Sorry that I do not understand what "memory location" means. You probably did not understand the state of this environment.

CartPole-v0 is a super simple environment where the state is formed by a 4 dimensional space. They are [cart location, cart velocity, pole angle, pole angular velocity].

As for the state of gym-chrome-dino, it is an 150x600x3 RGB image, which is a super high dimensional space. If you're doing a deep reinforcement learning, you need a convolutional network to handle this kind of state. Otherwise, you might need to use some techniques to extract features from the image so as to apply the traditional reinforcement methods.

By the way, `env` is not an agent but an environment.

**Comment by jeffasante** [comment]
Anyways thanks.
